services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./seafile-data:/seafile
      - ./nginx-logs:/logs
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db-data:/var/lib/mysql

  app:
    image: ubuntu:20.04
    tty: true
    command: bash
    working_dir: /seafile
    volumes:
      - ./seafile-data:/seafile
    environment:
      - TZ=Europe/Berlin
