services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - seafile-data:/seafile
      - nginx-logs:/logs
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql

  app:
    # build: .
    image: seafos
    # For external NGINX, use these:
    # ports:
    #   - 8000:8000
    #   - 8082:8082
    #   - 8080:8080
    volumes:
      - seafile-data:/seafile
      - ./downloads:/downloads
    environment:
      - TZ=Europe/Berlin
    # Uncomment these during install:
    tty: true
    entrypoint: bash
    command: []

volumes:
  seafile-data:
  db-data:
  nginx-logs: